//these are speed limits for non-truck vehicles in urban interstates and
// we will be using this as a reference until we use the google maps api
Map<String, int> speed_limit = {
  'Alabama':65,
  'Alaska':55,
  'American Samoa':65,
  'Arizona':65,
  'Arkansas':65,
  'California':65,
  'Colorado':65,
  'Connecticut':55,
  'Delaware':55,
  'District of Columbia':55,
  // 'Federated States of Micronesia',
  'Florida':65,
  'Georgia':70,
  // 'Guam',
  'Hawaii':60,
  'Idaho':75,
  'Illinois':55,
  'Indiana':55,
  'Iowa':55,
  'Kansas':75,
  'Kentucky':65,
  'Louisiana':70,
  'Maine':75,
  // 'Marshall Islands',
  'Maryland':70,
  'Massachusetts':65,
  'Michigan':70,
  'Minnesota':65,
  'Mississippi':70,
  'Missouri':60,
  'Montana':65,
  'Nebraska':70,
  'Nevada':65,
  'New Hampshire':65,
  'New Jersey':55,
  'New Mexico':75,
  'New York':65,
  'North Carolina':70,
  'North Dakota':75,
  // 'Northern Mariana Islands',
  'Ohio':65,
  'Oklahoma':70,
  'Oregon':55,
  // 'Palau',
  'Pennsylvania':70,
  // 'Puerto Rico',
  'Rhode Island':55,
  'South Carolina':70,
  'South Dakota':80,
  'Tennessee':70,
  'Texas':75,
  'Utah':65,
  'Vermont':55,
  // 'Virgin Island',
  'Virginia':55,
  'Washington':60,
  'West Virginia':55,
  'Wisconsin':70,
  'Wyoming':75
};
is_above_speed_limit(String state, double speed){
  if (speed_limit[state]!>speed) {
    return true;
  }
}